services:
  emerald-node:
    network_mode: host
    image: emerald:latest
    volumes:
      - ./nodes/${NODE_ID}:/home/emerald/.emerald
      - ./.testnet/config/${NODE_ID}:/home/emerald/.emerald/emerald
      - ./assets/jwtsecret:/home/emerald/jwt
    environment:
      - NODE_ID=${NODE_ID}
    command:
      - "start"
      - "--home=/home/emerald/.emerald"
      - "--config=/home/emerald/.emerald/emerald/config.toml"

volumes:
  emerald-data-0:
  emerald-data-1:
  emerald-data-2:
  emerald-data-3:
  emerald-data-4:
  emerald-data-5:
  emerald-data-6:
  emerald-data-7:
