name: Bug report
description: Create a bug report
title: "[Bug]: "
labels: ["bug", "status: waiting-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug in Emerald. 
        Please include as much detail as possible to help us reproduce and fix the issue quickly.

  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search existing issues to avoid creating duplicates.
      options:
        - label: I have searched the existing issues
          required: true

  - type: markdown
    attributes:
      value: |
        IMPORTANT: If you discover a security vulnerability in Emerald, 
        please report it **privately** and **DO NOT** open a public GitHub issue.
        See `SECURITY.md` for more details.

  - type: textarea
    id: what-happened
    attributes:
      label: Describe the bug
      description: |
        A clear and concise description of what the bug is. 
        Also tell us, what did you expect to happen?
    validations:
      required: true

  - type: input
    attributes:
      label: What version/commit are you on?
      description: Specify the version you're using
      placeholder: v0.1.0
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: |
        Please provide any steps you think might be relevant to reproduce the bug.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: If applicable, please provide the logs leading up to the bug.
    validations:
      required: false
