{
 "title": "Malachite + Reth",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  { "title": "Malachite", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "malachitebft_core_consensus_height",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "malachitebft_core_consensus_height",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "malachitebft_core_consensus_height (rate)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "rate(malachitebft_core_consensus_height[$__rate_interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "malachitebft_core_consensus_time",
   "type": "timeseries",
   "description": "malachitebft_core_consensus_consensus_time Consensus time, in seconds.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (job) (\n  rate(malachitebft_core_consensus_consensus_time_sum[$__rate_interval])\n) \n/ \nsum by (job) (\n  rate(malachitebft_core_consensus_consensus_time_count[$__rate_interval])\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "malachitebft_core_consensus_time_per_block_sum",
   "type": "timeseries",
   "description": "Time taken to finalize a block, in seconds.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (job) (\n  rate(malachitebft_core_consensus_time_per_block_sum[$__rate_interval])\n) \n/ \nsum by (job) (\n  rate(malachitebft_core_consensus_time_per_block_count[$__rate_interval])\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "malachitebft_core_consensus_rebroadcast_timeouts (rate)",
   "type": "timeseries",
   "description": "malachitebft_core_consensus_time_per_block Time taken to finalize a block, in seconds.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "rate(malachitebft_core_consensus_rebroadcast_timeouts_total[$__rate_interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "malachitebft_core_consensus_round",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "expr": "malachitebft_core_consensus_round",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "app_channel_db_write_bytes_total_total",
   "type": "timeseries",
   "description": "# HELP app_channel_db_write_bytes_total Amount of data written to the database (bytes).",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(app_channel_db_write_bytes_total_total[$__rate_interval])",
     "legendFormat": "{{job}}-Inbound"
    }
   ]
  },
  {
   "title": "app_channel_db_read_bytes_total",
   "type": "timeseries",
   "description": "# HELP app_channel_db_read_bytes_total Amount of data read from the database (bytes).",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(app_channel_db_read_bytes_total_total[$__rate_interval])",
     "legendFormat": "{{job}}-Inbound"
    }
   ]
  },
  {
   "title": "malachitebft_network_libp2p_bandwidth_bytes_total",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(malachitebft_network_libp2p_bandwidth_bytes_total{direction=\"Inbound\"}[$__rate_interval])",
     "legendFormat": "{{job}}-Inbound"
    },
    {
     "expr": "rate(malachitebft_network_libp2p_bandwidth_bytes_total{direction=\"Outbound\"}[$__rate_interval])",
     "legendFormat": "{{job}}-Outbound"
    }
   ]
  },
  {
   "title": "malachitebft_discovery_num_active_peers",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "malachitebft_discovery_num_active_peers",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Reth", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "reth_blockchain_tree_canonical_chain_height",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "reth_blockchain_tree_canonical_chain_height",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "reth_consensus_engine_beacon_executed_blocks",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "reth_consensus_engine_beacon_executed_blocks",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "reth_transaction_pool_inserted_transactions",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "rate(reth_transaction_pool_inserted_transactions[$__rate_interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "reth_blockchain_tree_in_mem_state_num_blocks",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "reth_blockchain_tree_in_mem_state_num_blocks",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "reth_transaction_pool_pending_pool_size_bytes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "reth_transaction_pool_pending_pool_size_bytes",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "reth_transaction_pool_pending_pool_transactions",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "reth_transaction_pool_pending_pool_transactions",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "reth_transaction_pool_queued_pool_transactions",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "reth_transaction_pool_queued_pool_transactions",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "reth_engine_rpc_forkchoice_updated_messages not valid",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "expr": "reth_engine_rpc_forkchoice_updated_messages-reth_engine_rpc_forkchoice_updated_valid",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "reth_transaction_pool_performed_state_updates",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "reth_transaction_pool_performed_state_updates",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "reth_engine_rpc_get_payload_v3_count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "rate(reth_engine_rpc_get_payload_v3_count[$__rate_interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "reth_network_connected_peers",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 56 },
   "targets": [
    { "expr": "reth_network_connected_peers", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "reth_engine_rpc_new_payload_messages not valid",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "reth_engine_rpc_new_payload_messages-reth_engine_rpc_new_payload_valid",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "reth_network_pool_transactions_messages_sent_total",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "reth_network_pool_transactions_messages_sent_total",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "reth_network_pool_transactions_messages_received_total",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 61 },
   "targets": [
    {
     "expr": "rate(reth_network_pool_transactions_messages_received_total[$__rate_interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "reth_io_write_bytes (rate)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(reth_io_write_bytes[$__rate_interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "reth_io_read_bytes (rate)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(reth_io_read_bytes[$__rate_interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "reth_sync_execution_execution_duration",
   "type": "timeseries",
   "description": "The total amount of time it took to execute the latest block.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "reth_sync_execution_execution_duration",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "reth_payloads_initiated_payload_builds",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 71 },
   "targets": [
    {
     "expr": "reth_payloads_initiated_payload_builds",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "reth_transaction_pool_blob_base_fee",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 76 },
   "targets": [
    {
     "expr": "reth_transaction_pool_blob_base_fee",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "reth_blockchain_tree_reorgs",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 76 },
   "targets": [
    { "expr": "reth_blockchain_tree_reorgs", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "reth_transaction_pool_base_fee",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 81 },
   "targets": [
    { "expr": "reth_transaction_pool_base_fee", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "reth_transaction_pool_invalid_transactions",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 81 },
   "targets": [
    {
     "expr": "reth_transaction_pool_invalid_transactions",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}