pub mod validator_manager;

pub use validator_manager::{
    ValidatorManager, ValidatorManagerProxy,
    GENESIS_ACCOUNT as GENESIS_VALIDATOR_MANAGER_ACCOUNT,
    GENESIS_IMPL_ACCOUNT as GENESIS_VALIDATOR_MANAGER_IMPL_ACCOUNT,
    UUPS_SELF_IMMUTABLE_LENGTH, UUPS_SELF_IMMUTABLE_OFFSETS,
};
